-- Create a table for offers
create table offers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  start_date date,
  end_date date,
  image_url text,
  is_active boolean default true
);

-- Set up Row Level Security (RLS)
alter table offers enable row level security;

-- Policy: Anyone can view active offers
create policy "Public offers are viewable by everyone."
  on offers for select
  using ( is_active = true );

-- Policy: Service role or authenticated users can do everything
-- Note: For this simple app, we'll allow authenticated users (owner) to manage offers.
create policy "Authenticated users can manage offers."
  on offers for all
  using ( auth.role() = 'authenticated' );

-- Create a storage bucket for offer images
insert into storage.buckets (id, name, public)
values ('offer-images', 'offer-images', true);

-- Policy: Anyone can view images
create policy "Offer images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'offer-images' );

-- Policy: Authenticated users can upload images
create policy "Authenticated users can upload offer images."
  on storage.objects for insert
  with check ( bucket_id = 'offer-images' and auth.role() = 'authenticated' );

-- Policy: Authenticated users can update images
create policy "Authenticated users can update offer images."
  on storage.objects for update
  using ( bucket_id = 'offer-images' and auth.role() = 'authenticated' );

-- Policy: Authenticated users can delete images
create policy "Authenticated users can delete offer images."
  on storage.objects for delete
  using ( bucket_id = 'offer-images' and auth.role() = 'authenticated' );
